# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 408d082f0f073341edf5311e8a12a44b34bc599178a076126117472f582b0155b90404425f4c59b6c76ba3911ade23789bfbf26efc737794445811978d6f1192

test:
  secret_key_base: 74285450ac0cec98373d22d364785aeb254149f32061dc12004679bb94841fe778a17b6634e10b1c7e96433cc65721a3a26f1f43194791c4eba4fa975852d6ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
